version: '3.3'

services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.1-ubuntu2204
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Mongo@123
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
    restart: on-failure
volumes:
  mongodb:
    driver: local