spring:
  application:
    name: sample-project

server:
  port: 8080
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample-db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Admin@123
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        auto_quote_keyword: true
    show-sql: true

#logging:
#  level:
##    root: DEBUG
#    org.springframework.security: trace

---
reqres:
  url: https://reqres.in
