spring:
  application:
    name: sample-project

server:
  port: 8080
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Admin@123
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        auto_quote_keyword: true
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: DEBUG
    org.springframework.security: trace

---
spring:
  cache:
    cache-names: USER
    type: redis
    redis:
      time-to-live: PT2M
  data:
    redis:
      host: localhost
      port: 6379
      password: Redis@123
---
reqres:
  url: https://reqres.in