version: '3.3'

services:
  mysql-db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
#      MYSQL_DATABASE: auth
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
    - '3306:3306'
    volumes:
    - mysql-db:/var/lib/mysql
    restart: on-failure

volumes:
  mysql-db:
    driver: local
